runtime: java11
env: standard
runtime_config:
  jdk: openjdk11

env_variables:
  SPRING_PROFILES_ACTIVE: "production"

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_concurrent_requests: 1

handlers:
- url: /.*
  script: auto
  http_headers:
    Access-Control-Allow-Origin: *